### ISSUE TITLE
how to debug this error?

### ISSUE THREAD

**Issue by Otoliths** [tomleung1996/wos_crawler#1]
Hi TomLeung,
E:\project_python\venv\Scripts\python.exe E:/project_python/alpha/wos_crawler/main.py
Traceback (most recent call last):
  File "E:/project_python/alpha/wos_crawler/main.py", line 1, in <module>
    from wos_crawler.gui.main_gui import *
ImportError: No module named 'wos_crawler'

Process finished with exit code 1

how to debug this error?

**Comment by tomleung1996** [comment]
Bug fixed.
抱歉，我之前一直是在本地的Pycharm环境下进行开发和使用，没有打包测试的经验。查出来是SourceRoot的设置问题，已经将全部带有wos_crawler的import修正了，你看看能不能正常使用？

**Comment by Otoliths** [comment]
OK，谢谢了，减少不少工作量




| |
丁刘勇
|
|
邮箱：ly_ding@126.com
|

签名由 网易邮箱大师 定制

On 01/19/2019 17:30, TomLeung wrote:

Bug fixed.
抱歉，我之前一直是在本地的Pycharm环境下进行开发和使用，没有打包测试的经验。查出来是SourceRoot的设置问题，已经将全部带有wos_crawler的import修正了，你看看能不能正常使用？

**Comment by tomleung1996** [comment]
下午的时候我更新了一下功能和逻辑，你可以看看
