### ISSUE TITLE
请问，按检索式检索时报错[scrapy.core.scraper] ERROR: Spider error processing如何解决

### ISSUE THREAD

**Issue by XUHANLIN** [tomleung1996/wos_crawler#10]
大神好，我在用检索式检索时报出如下错误：
<img width="984" alt="截屏2020-04-22下午3 13 47" src="https://user-images.githubusercontent.com/16678482/79952266-bb4f5000-84ac-11ea-8e5c-812727d33cc5.png">

main.py中相应的代码段如下：
if __name__ == '__main__':
 
    # 按检索式下载
    crawl_by_query(query='TS=(neurofibroma) AND PY=(2000-2020)',
                    output_path='../output', output_format='fieldtagged', document_type='Article', sid='8AUSx4HeIpAe8s47N3o')

    pass

wos检索界面的URL如下：
https://apps.webofknowledge.com/Search.do?product=WOS&SID=8AUSx4HeIpAe8s47N3o&search_mode=GeneralSearch&prID=7a0958cd-c445-457c-8b6e-9e6db36d9ea9

运行平台：MacOs Catalina 10.15.2

**Comment by XUHANLIN** [comment]
突然又自己好了哈哈😄

**Comment by jtydq** [comment]
我也是这个错误 一直没好 555
