### ISSUE TITLE
建议增加详细的 requirements.txt

### ISSUE THREAD

**Issue by luoluo1997a** [tomleung1996/wos_crawler#11]
Tomleung1996 你好，

首先感谢你开源这个项目，它真的很棒，但是我在使用过程中发现由于缺少必要的requirements.txt，导致我需要一步一步安装每一个依赖包，这让我使用起来耗费了很多不必要的时间和精力，可以考虑生成一个详细的完整的requirements.txt便于以后的使用吗？

非常感谢！

**Comment by tomleung1996** [comment]
您好，感谢你的使用。
这个工具在开发的时候没有使用单独的虚拟环境，所以requirements的生成有点麻烦（会把我环境中所有包都加进去了）
我对这方面不是很了解，想问下您有没有比较好的解决办法？
