### ISSUE TITLE
作者大大，使用时遇到一个无法处理请求的问题，详见下图，想问一下有解决思路吗

### ISSUE THREAD

**Issue by KLancelot** [tomleung1996/wos_crawler#12]
![image](https://user-images.githubusercontent.com/13092699/82758106-2b882300-9e17-11ea-8de1-5038f1cc14fc.png)

**Comment by tomleung1996** [comment]
建议重试或者把完整错误放出来

**Comment by jtydq** [comment]
同 我也是这个错误
![1629871090(1)](https://user-images.githubusercontent.com/82260762/130750841-983bd437-1e9e-4b7d-9682-10ff7b974433.png)
