### ISSUE TITLE
How to custom the year range?

### ISSUE THREAD

**Issue by lowspace** [tomleung1996/wos_crawler#13]
In advanced search mode, users can custom the year range of their queries, but how?

**Comment by tomleung1996** [comment]
Just enter a valid Web of Science search query will do the job. Please check the WoS document of how to construct your advanced query.

For example, you could get the papers published on _Nature_  between 2018 and 2019 with this query:
`SO=(Nature) AND PY=(2018-2019)`

**Comment by lowspace** [comment]
> Just enter a valid Web of Science search query will do the job. Please check the WoS document of how to construct your advanced query.
> 
> For example, you could get the papers published on _Nature_ between 2018 and 2019 with this query:
> `SO=(Nature) AND PY=(2018-2019)`

thx~ I find editing code in line 119 and line 120 of `wos_crawler/spiders/wos_advanced_query_spider.py` also can solve this issue, but much more complex.

**Comment by tomleung1996** [comment]
No need to modify the spiders. And I don't recommend doing so.

**Comment by lowspace** [comment]
> No need to modify the spiders. And I don't recommend doing so.

Get it, thx for replying.
