### ISSUE TITLE
似乎不能爬取2018年以后的论文信息？

### ISSUE THREAD

**Issue by mayizan** [tomleung1996/wos_crawler#17]
感谢编者的文献爬取利器，但似乎只能爬取2018年以前收录的论文信息？我尝试了多本杂志，都只能获取2018年以前的论文集，是否有相应的参数可以修改？
![image](https://user-images.githubusercontent.com/50535606/93887230-051cba80-fd19-11ea-97cf-a48f8c5d7eaf.png)

**Comment by tomleung1996** [comment]
您好，因为本爬虫写于2018年，期刊爬虫里面的query字符串为检索式，可以自行修改一下年份。谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mayizan <notifications@github.com&gt;
发送时间: 2020年9月22日 21:18
收件人: tomleung1996/wos_crawler <wos_crawler@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tomleung1996/wos_crawler] 似乎不能爬取2018年以后的论文信息？ (#17)





 
感谢编者的文献爬取利器，但似乎只能爬取2018年以前收录的论文信息？我尝试了多本杂志，都只能获取2018年以前的论文集，是否有相应的参数可以修改？

**Comment by mayizan** [comment]
感谢编者。已经修改，成功爬取到最新论文。
祝好！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 马益赞
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2020.9.22




------------------&nbsp;Original&nbsp;------------------
