### ISSUE TITLE
超过10万条分批下载后再同时解析存入Sqlite

### ISSUE THREAD

**Issue by keithkang1986** [tomleung1996/wos_crawler#21]
请问检索结果超过10万条后，采用了分批量下载的方法，怎样才能把分批量下载结果放在同一个文件夹中再同时解析，并存入一个数据库？谢谢！

**Comment by tomleung1996** [comment]
放到同一个文件夹（可以嵌套文件夹）然后调用单独的解析程序即可，注意修改路径
