### ISSUE TITLE
假如想选择特定的数据库进行检索，应该如何修改代码

### ISSUE THREAD

**Issue by qihaoxiaoai** [tomleung1996/wos_crawler#22]
感谢作者，可以顺利运行程序，但是还有一个问题：
1.关于时间修改的操作已经掌握
2.但是程序默认检索与下载的是所有已经购买的数据库的资料，加入我只想选择一个，应该如何修改代码呢
![image](https://user-images.githubusercontent.com/29853695/116808093-971b5a00-ab69-11eb-8850-f35d66c8fd24.png)

**Comment by tomleung1996** [comment]
wos_advanced_query_spider.py第89行修改为你想要的数据库，要使用列表

**Comment by qihaoxiaoai** [comment]
> wos_advanced_query_spider.py第89行修改为你想要的数据库，要使用列表

顺利解决问题，谢谢作者！非常棒的爬虫
