### ISSUE TITLE
【已解决】请问：执行main.py时报错ReactorAlreadyInstalledError: reactor already installed怎么解决

### ISSUE THREAD

**Issue by XUHANLIN** [tomleung1996/wos_crawler#9]
大神您好，请问我执行main.py报出这个错误该怎么解决呀
![WechatIMG609](https://user-images.githubusercontent.com/16678482/79880392-85fe2000-8422-11ea-86b1-21dd8a332077.jpeg)

平台：macOS Catalina 10.15.2
下载日期：2020.4.21

**Comment by tomleung1996** [comment]
这个问题我很久之前遇到过一次，但是自己好了，可能是和环境有关的。试一下用终端直接启动，不要用IDE

**Comment by XUHANLIN** [comment]
解决啦，谢谢您
